<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJCSO1Ta\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJCSO1Ta/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJCSO1Ta.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJCSO1Ta\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerJCSO1Ta\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'JCSO1Ta',
    'container.build_id' => '9b332c38',
    'container.build_time' => 1681151879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJCSO1Ta');
